[project]
name = "pytest-elefast"
version = "0.1.0"
description = "Pytest integration for elefast"
readme = "README.md"
authors = [
    { name = "Niclas van Eyk", email = "niclas.eyk@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[project.entry-points.pytest11]
pytest-fixed = "pytest_elefast.pytest_entrypoint"
