[project]
name = "elefast-core"
version = "0.1.0"
description = "The core logic for elefast"
readme = "README.md"
authors = [
    { name = "Niclas van Eyk", email = "niclas.eyk@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
